spring:
  cloud:
    gateway:
      routes:
      - id: admin-route
        uri: http://localhost:8081
        predicates:
        - Path= /api/v1.0/flight/airline/**
      - id: user_route
        uri: http://localhost:8083
        predicates:
        - Path= /api/v1.0/user/**
      - id: flight_route
        uri: http://localhost:8082
        predicates:
        - Path=/api/v1.0/common/flight/**
  application:
    name: flight-api-gateway
server:  port: 8084
management:  endpoints:    web:      exposure:        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
  
